<?php
/**
 * MediaWiki LocalSettings for E2E testing.
 * Used by the Docker Compose setup — not for production.
 */

# Base settings (generated by install.php, then overridden here).
$wgSitename = 'InstantIIIF Test Wiki';
$wgServer = 'http://localhost:8080';
$wgScriptPath = '';
$wgArticlePath = '/wiki/$1';

# SQLite database (created by install.php).
$wgDBtype = 'sqlite';
$wgDBname = 'testwiki';
$wgSQLiteDataDir = '/var/www/data';

# Disable caching for test predictability.
$wgMainCacheType = CACHE_NONE;
$wgSessionCacheType = CACHE_NONE;
$wgCacheDirectory = false;
$wgObjectCaches['default'] = ['class' => HashBagOStuff::class];

# Enable uploads dir (required for FileRepo).
$wgUploadDirectory = '/var/www/html/images';
$wgUploadPath = '/images';

# Secret key (test-only, not sensitive).
$wgSecretKey = 'e2e-test-secret-key-not-for-production-0123456789abcdef';
$wgUpgradeKey = 'e2e-test-upgrade-key';

# Disable email.
$wgEnableEmail = false;

# Load Vector skin (default in MW 1.44).
wfLoadSkin( 'Vector' );

# Enable MultimediaViewer (comes with MW core since 1.44).
wfLoadExtension( 'MultimediaViewer' );
$wgMediaViewerEnableByDefault = true;

# Load InstantIIIF.
wfLoadExtension( 'InstantIIIF' );

# Configure IIIF provider pointing to the mock server.
$wgForeignFileRepos[] = [
    'name' => 'iiif-test',
    'class' => \MediaWiki\Extension\InstantIIIF\Repo::class,
    'directory' => '/tmp/iiif-repo',
    'hashLevels' => 0,
    'iiifSources' => [
        [
            'id' => 'deutsche-fotothek',
            'manifestPattern' => 'http://iiif-mock:8111/iiif/2/$1/manifest.json',
        ],
    ],
];

# Shorter timeout for tests.
$wgInstantIIIFDefaultTimeout = 10;

# Debug (useful when tests fail).
$wgShowDBErrorBacktrace = true;
$wgShowExceptionDetails = true;
