<?php
/**
 * MediaWiki LocalSettings for E2E testing.
 * Used by the Docker Compose setup — not for production.
 */

# Base settings (generated by install.php, then overridden here).
$wgSitename = 'InstantIIIF Test Wiki';
$wgServer = 'http://localhost:8080';
$wgScriptPath = '';
$wgArticlePath = '/wiki/$1';

# SQLite database (created by install.php).
$wgDBtype = 'sqlite';
$wgDBname = 'testwiki';
$wgSQLiteDataDir = '/var/www/data';

# Disable object caching for test predictability.
$wgMainCacheType = CACHE_NONE;
$wgSessionCacheType = CACHE_NONE;
$wgMessageCacheType = CACHE_NONE;
$wgJobTypeConf['default'] = [ 'class' => 'JobQueueMemory' ];
$wgObjectCaches['default'] = ['class' => HashBagOStuff::class];

# Use file-based localisation cache to avoid SQLite contention.
# Without this, concurrent requests to load.php and index.php cause
# DBTransactionStateError which breaks ALL ResourceLoader modules.
$wgCacheDirectory = '/tmp/mw-cache';
$wgLocalisationCacheConf['store'] = 'file';
$wgLocalisationCacheConf['manualRecache'] = false;

# Enable uploads dir (required for FileRepo).
$wgUploadDirectory = '/var/www/html/images';
$wgUploadPath = '/images';

# Secret key (test-only, not sensitive).
$wgSecretKey = 'e2e-test-secret-key-not-for-production-0123456789abcdef';
$wgUpgradeKey = 'e2e-test-upgrade-key';

# Disable email.
$wgEnableEmail = false;

# Load Vector skin (default in MW 1.44).
wfLoadSkin( 'Vector' );

# Enable MultimediaViewer (comes with MW core since 1.44).
wfLoadExtension( 'MultimediaViewer' );
$wgMediaViewerEnableByDefault = true;

# Enable VisualEditor. VE's "Insert media" dialog is the path that
# exercises resources/media-search.js, # so it must be present for the
# media-search e2e tests.
wfLoadExtension( 'VisualEditor' );
$wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgVisualEditorEnableWikitext = true;
# Suppress the one-time "beta welcome" dialog so it doesn't intercept the
# media-insert dialog in e2e tests.
$wgVisualEditorShowBetaWelcome = false;

# Load InstantIIIF.
wfLoadExtension( 'InstantIIIF' );

# Configure IIIF provider pointing to the mock server.
$wgForeignFileRepos[] = [
    'name' => 'iiif',
    'class' => \MediaWiki\Extension\InstantIIIF\Infrastructure\MediaWiki\Repo::class,
    'directory' => '/tmp/iiif-repo',
    'hashLevels' => 0,
    # Local image caching defaults ON. It is disabled here so the e2e suite
    # keeps asserting the provider-hotlink URLs (enabling it rewrites thumbnail
    # and full-image URLs to local /images/iiif-cache/ copies). To exercise the
    # cached path, set this to e.g. 31536000 and ensure the thumb zone is both
    # writable and web-served (point `directory` at $wgUploadDirectory, or add a
    # server alias for the cache URL).
    'imageCacheExpiry' => 0,
    'iiifSources' => [
        [
            'id' => 'deutsche-fotothek',
            'idPattern' => '/^df_[a-z0-9_-]+$/i',
            'manifestPattern' => 'http://iiif-mock:8111/iiif/2/$1/manifest.json',
        ],
    ],
];

# Shorter timeout for tests.
$wgInstantIIIFDefaultTimeout = 10;

# Debug (useful when tests fail).
$wgShowDBErrorBacktrace = true;
$wgShowExceptionDetails = true;
