name: Quality assurance Assets
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.js'
      - '**.md'
jobs:
  wp-scripts-lint:
    uses: inpsyde/reusable-workflows/.github/workflows/wp-scripts-lint.yml@main
    with:
      LINT_TOOLS: '["js", "md-docs"]'
